// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drenskqwbibygwqlqorh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZW5za3F3YmlieWd3cWxxb3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjIwOTUsImV4cCI6MjA2NzYzODA5NX0.tiQa1K1IscljXw2Dq0XC_D0q6ZDiEZNGWi7UI84Pnis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});